# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
   echo Write your commands here
   
   echo Hello world
   
   docker images
   
   docker build -t hellofargate ./HelloFargate

   docker images
  displayName: 'Command Line Script'
- task: SlackPoster@2
  inputs:
    UserName: 'Azure to AWS'
    Message: 'AWS deployment started'
    ApiToken: 'xoxp-645208011568-756078985317-781517236146-531344d110338276248062e788e6b078'
    Channel: 'e2etraceability'
    IconUrl: 'devops-traceablity'
    NeverFails: false
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: 'hellofargate'
    repositoryName: 'devopsdemolatest'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'us-east-1'
    awsCommand: 'ecs'
    awsSubCommand: 'update-service'
    awsArguments: '--cluster hellofargate --service hellofargateservice --force-new-deployment'

- task: SlackPoster@2
  inputs:
    UserName: 'Azure to AWS'
    Message: 'AWS deployment completed'
    ApiToken: 'xoxp-645208011568-756078985317-781517236146-531344d110338276248062e788e6b078'
    Channel: 'e2etraceability'
    IconUrl: 'devops-traceablity'
    NeverFails: false